<section class="page-header">
	<h1 class="project-name">Cayman</h1>
	<h2 class="project-tagline">A responsive theme for your project on GitHub Pages</h2>
	<a href="#" class="btn">View on GitHub</a>
	<a href="#" class="btn">Download .zip</a>
	<a href="#" class="btn">Download .tar.gz</a>
</section>
<section class="main-content">
	<footer class="site-footer">
		<span class="site-footer-owner"><a href="https://github.com/jasonlong/cayman-theme">Cayman</a> is maintained by <a href="https://github.com/jasonlong">jasonlong</a>.</span>
		<span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
	</footer>
</section>
